version: '3'
services:
  db:
    image: "mariadb:10"
    ports:
      - "4000:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foodin

volumes:
  db-data:
